//
//  MovieInfoRouter.swift
//  inmovie
//
//  Created Константин on 04/12/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//

import Foundation
import UIKit

class MovieInfoRouter: MovieInfoRouterProtocol {
    
    weak var viewController: MovieInfoViewController!
    
    init(viewController: MovieInfoViewController) {
        self.viewController = viewController
    }
    
}
