//
//  MovieInfoInteractor.swift
//  inmovie
//
//  Created Константин on 04/12/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//


import Foundation
import UIKit

class MovieInfoInteractor: MovieInfoInteractorProtocol {
    

    /*
     * Сервис загрузки бибилиотеки
     */
    var libraryService: LibraryServiceProtocol!
    
    weak var presenter: MovieInfoPresenterProtocol!
    
    required init(presenter: MovieInfoPresenterProtocol) {
        self.presenter = presenter
    }
}

extension MovieInfoInteractor {

    func loadMovieInfo(withId id: Int) {
        self.libraryService.loadMovieInfo(withId: id, completion: { [weak self] (movieInfoRecived) in
            self?.presenter?.movieInfoDidRecive(info: movieInfoRecived)
        })
    }
    
}
