//
//  MovieInfoConfigurator.swift
//  inmovie
//
//  Created Константин on 04/12/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//

import Foundation
import UIKit

class MovieInfoConfigurator: MovieInfoConfiguratorProtocol {
    
    func configure(with viewController: MovieInfoViewController) {
        let presenter = MovieInfoPresenter(view: viewController)
        let interactor = MovieInfoInteractor(presenter: presenter)
        let router = MovieInfoRouter(viewController: viewController)
        
        viewController.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
        
        // Сервисы
        interactor.libraryService = LibraryService()
    }
}
