//
//  MovieListPresenter.swift
//  inmovie
//
//  Created Константин on 27/11/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//

import Foundation

class MovieListPresenter: MovieListPresenterProtocol {

    
    weak var view: MovieListViewProtocol!
    var interactor: MovieListInteractorProtocol!
    var router: MovieListRouterProtocol!
    
    required init(view: MovieListViewProtocol) {
        self.view = view
    }
    
    // MARK: - MovieListPresenterProtocol методы
    
    func configureView() {
        interactor.loadMovieList(genre: 0)
    }
    
    
    /**
     Метод отвечает за подготовку данных для вью после получения списка фильмов
     
     - Parameter movies: Массив фильмов полученных от сервера
     */
    func movieListDidRecive(movies: [FeaturedMoviesSection]) {
        var sectionsCellModels: [FeaturedMoviesSectionCellModel] =  [FeaturedMoviesSectionCellModel]()
        movies.forEach {
            let sectionCelldModel = FeaturedMoviesSectionCellModel($0)
            sectionCelldModel.delegate = self
            sectionsCellModels.append(sectionCelldModel)
        }
        //print(moviesCellModels[0].overview)
        view.updateMovieList(sections: sectionsCellModels)
    }
    
    
}

// MARK: - MovieCellModelDelegate методы

extension MovieListPresenter: FeaturedSectionModelDelegate {
    
    
    func didTapMovieCell(withId: Int) {
        router.showMovieInfo(id: withId)
    }
    
    
}
