//
//  MovieListConfigurator.swift
//  inmovie
//
//  Created Константин on 27/11/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//

import Foundation
import UIKit

class MovieListConfigurator: MovieListConfiguratorProtocol {
    
    func configure(with viewController: MovieListViewController) {
        let presenter = MovieListPresenter(view: viewController)
        let interactor = MovieListInteractor(presenter: presenter)
        let router = MovieListRouter(viewController: viewController)
        
        viewController.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
    }
}
