//
//  MovieListInteractor.swift
//  inmovie
//
//  Created Константин on 27/11/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//


import Foundation
import UIKit

class MovieListInteractor: MovieListInteractorProtocol {

    
    /*
     * Сервис загрузки бибилиотеки
     */
    var libraryService: LibraryServiceInterface!
    
    /**
     Загрузка списка фильмов
     
     - Parameter genre:
     */
    func loadMovieList(genre: Int = 0) {
        self.libraryService.loadMoviesList(genre: genre, completion: { [weak self] (moviesRecived) in
            self?.presenter?.movieListDidRecive(movies: moviesRecived)
        })
    }
    
    
    weak var presenter: MovieListPresenterProtocol!
    
    required init(presenter: MovieListPresenterProtocol) {
        self.presenter = presenter
    }
}
