//
//  MovieListViewController.swift
//  inmovie
//
//  Created Константин on 27/11/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//

import UIKit

class MovieListViewController: UIViewController, MovieListViewProtocol {
    
    var presenter: MovieListPresenterProtocol!
    let configurator: MovieListConfiguratorProtocol = MovieListConfigurator()
    
    // MARK: - Lifecycle methods
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        presenter.configureView()
    }
    
    
}
