//
//  MovieListRouter.swift
//  inmovie
//
//  Created Константин on 27/11/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//

import Foundation
import UIKit

class MovieListRouter: MovieListRouterProtocol {

    
    
    weak var viewController: MovieListViewController!
    
    init(viewController: MovieListViewController) {
        self.viewController = viewController
    }
    
    func showMovieInfo(id: Int)  {
        let nextViewController = MovieInfoViewController()
        nextViewController.id = id
        viewController.navigationController?.pushViewController(nextViewController, animated: true)
    }
    
}
