//
//  MovieListInteractor.swift
//  inmovie
//
//  Created Константин on 27/11/2018.
//  Copyright © 2018 Константин. All rights reserved.
//
//  Template generated by Tundaikin Konstantin
//


import Foundation
import UIKit

class MovieListInteractor: MovieListInteractorProtocol {
    
    weak var presenter: MovieListPresenterProtocol!
    
    required init(presenter: MovieListPresenterProtocol) {
        self.presenter = presenter
    }
}
